# pipeline {
#     agent { docker { image 'node:20.15.1-alpine3.20' } }
#     stages {
#        stage('build') {
#             steps {
#                 sh 'node --version'
#             }
#         }
#     }
# }

pipeline {
    agent any
    stages {
        stage('Example Stage') {
            steps {
                echo 'Hello, Pipeline!'
            }
        }
    }
}
