node {
	try {
		stage('Checkout') {
			checkout scm
		}

		stage('Build') {
			echo 'Buidling...'
		}

		stage('Test') {
			echo 'Testing...'
		}

		stage('Deploy') {
			echo 'Deploying...'

		}

	} catch (Exception e){
		currentBuild.result = 'Failure'
		throw e

	} finally {

	}
}
